apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: api-dev
  labels:
    app: poi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
        - name: poi
          image: 'registryqzm1711.azurecr.io/poi:latest'
          ports:
            - containerPort: 80
          env:
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: sqlusersecret
                  key: sqluser
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlpasswordsecret
                  key: sqlpassword
            - name: SQL_SERVER
              value: sqlserverqzm1711.database.windows.net
            - name: SQL_DBNAME
              value: mydrivingDB
            - name: WEB_PORT
              value: '80'
            - name: WEB_SERVER_BASE_URI
              value: 'http://0.0.0.0'
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: CONFIG_FILES_PATH
              value: /secrets
          #envFrom:
          #  - secretRef:
          #    name: {{name of your secret in kubernetes}}
          # not required, but recommended best practice
          livenessProbe:
            httpGet:
              path: '/api/poi/healthcheck' # hint: there is a healthcheck endpoint - read the README!
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: '/api/poi/healthcheck'
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: secrets-store-inline
              mountPath: '/mnt/secrets-store'
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: azure-kvname
            nodePublishSecretRef: # Only required when using service principal mode
              name: secrets-store-creds # Only required when using service principal mode
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api-dev
spec:
  type: ClusterIP #LoadBalancer
  selector:
    app: poi
  ports:
    - protocol: TCP
      name: poi-http
      port: 80 # port you hit
      targetPort: 80 # port inside
