apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  labels:
    app: tripviewer-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
        - name: tripviewer
          image: 'registryqzm1711.azurecr.io/tripviewer:latest'
          ports:
            - containerPort: 80
          env:
            - name: TRIPS_API_ENDPOINT
              value: ''
            - name: USERPROFILE_API_ENDPOINT
              value: ''
---
apiVersion: v1
kind: Service
metadata:
  name: poi
spec:
  type: ClusterIP #LoadBalancer
  selector:
    app: poi
  ports:
    - protocol: TCP
      name: poi-http
      port: 80 # port you hit
      targetPort: 80 # port inside
