apiVersion: apps/v1
kind: Deployment
metadata:
  name: poialk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poialk
  template:
    metadata:
      labels:
        app: poialk
    spec:
      nodeSelector:
        'beta.kubernetes.io/os': linux
      containers:
        - name: poialk
          image: registryqzm1711.azurecr.io/poi:latest
          env:
            - name: SQL_USER
              value: sqladminqZm1711
            - name: SQL_PASSWORD
              value: oH2ho8Ro3
            - name: SQL_SERVER
              value: sqlserverqzm1711.database.windows.net
            - name: SQL_DBNAME
              value: mydrivingDB
            - name: WEB_PORT
              value: '80'
            - name: WEB_SERVER_BASE_URI
              value: 'http://0.0.0.0'
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: CONFIG_FILES_PATH
              value: /secrets
          ports:
            - containerPort: 6379
              name: redis
