apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api-dev
  labels:
    app: trips-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
        - name: trips
          image: 'registryqzm1711.azurecr.io/trips:latest'
          ports:
            - containerPort: 80
          env:
            - name: SQL_USER
              value: sqladminqZm1711
            - name: SQL_PASSWORD
              value: oH2ho8Ro3
            - name: SQL_SERVER
              value: sqlserverqzm1711.database.windows.net
            - name: SQL_DBNAME
              value: mydrivingDB
            - name: OPENAPI_DOCS_URI
              value: 'http://localhost'
            - name: CONFIG_FILES_PATH
              value: /secrets
          #envFrom:
          #  - secretRef:
          #    name: {{name of your secret in kubernetes}}
          # not required, but recommended best practice
          livenessProbe:
            httpGet:
              path: '/api/trips/healthcheck' # hint: there is a healthcheck endpoint - read the README!
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: '/api/trips/healthcheck'
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          # resource limits are also best practice - I'll let you figure that out on your own
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api-dev
spec:
  type: ClusterIP #LoadBalancer
  selector:
    app: trips
  ports:
    - protocol: TCP
      name: trips-http
      port: 80 # port you hit
      targetPort: 80 # port inside
